In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import wbgapi as wb

In [4]:
wb.source.info()

id    name                                                                  code      concepts  lastupdated
----  --------------------------------------------------------------------  ------  ----------  -------------
1     Doing Business                                                        DBS              3  2021-08-18
2     World Development Indicators                                          WDI              3  2021-11-23
3     Worldwide Governance Indicators                                       WGI              3  2021-09-27
5     Subnational Malnutrition Database                                     SNM              3  2016-03-21
6     International Debt Statistics                                         IDS              4  2021-10-10
11    Africa Development Indicators                                         ADI              3  2013-02-22
12    Education Statistics                                                  EDS              3  2020-12-20
13    Enterprise Surveys                                                    ESY              3  2021-04-02
14    Gender Statistics                                                     GDS              3  2021-09-27
15    Global Economic Monitor                                               GEM              3  2020-07-27
16    Health Nutrition and Population Statistics                            HNP              3  2021-09-15
18    IDA Results Measurement System                                        IDA              3  2021-07-23
19    Millennium Development Goals                                          MDG              3  2018-09-19
20    Quarterly Public Sector Debt                                          PSD              3  2021-11-01
22    Quarterly External Debt Statistics SDDS                               QDS              3  2021-10-29
23    Quarterly External Debt Statistics GDDS                               QDG              3  2021-10-29
24    Poverty and Equity                                                    POV              3  2021-10-05
25    Jobs                                                                  JOB              3  2021-02-17
27    Global Economic Prospects                                             GEP              3  2021-06-08
28    Global Financial Inclusion                                            FDX              3  2018-10-15
29    The Atlas of Social Protection: Indicators of Resilience and Equity   GSP              3  2021-11-04
30    Exporter Dynamics Database â€“ Indicators at Country-Year Level         ED1              3  2016-03-31
31    Country Policy and Institutional Assessment                           CPI              3  2021-09-16
32    Global Financial Development                                          GFD              3  2021-12-03
33    G20 Financial Inclusion Indicators                                    G2F              3  2019-02-27
34    Global Partnership for Education                                      GPE              3  2013-04-12
35    Sustainable Energy for All                                            SE4              3  2018-06-30
36    Statistical Capacity Indicators                                       BBS              3  2021-02-03
37    LAC Equity Lab                                                        LEL              3  2016-04-06
38    Subnational Poverty                                                   SNP              3  2015-04-27
39    Health Nutrition and Population Statistics by Wealth Quintile         HNQ              3  2021-06-08
40    Population estimates and projections                                  HPP              3  2021-09-15
41    Country Partnership Strategy for India (FY2013 - 17)                  CPS              3  2015-05-22
43    Adjusted Net Savings                                                  WAT              3  2021-04-27
45    Indonesia Database for Policy and Economic Research                   IDD              3  2019-05-07
46    Sustainable Development Goals                                         SDG              3  2021-07-02
50    Subnational Population                                                SNT              3  2017-09-21
54    Joint External Debt Hub                                               JED              3  2021-11-29
57    WDI Database Archives                                                 WDA              4  2021-11-05
58    Universal Health Coverage                                             UHC              3  2019-04-25
59    Wealth Accounts                                                       WAC              3  2021-10-27
60    Economic Fitness                                                      EFT              3  2018-04-19
61    PPPs Regulatory Quality                                               PRQ              3  2019-04-25
62    International Comparison Program (ICP) 2011                           ICP              4  2020-08-24
63    Human Capital Index                                                   HCI              3  2020-09-21
64    Worldwide Bureaucracy Indicators                                      WBI              3  2021-05-26
65    Health Equity and Financial Protection Indicators                     HPI              3  2019-11-06
66    Logistics Performance Index                                           LPI              3  2019-10-29
67    PEFA 2011                                                             PF1              4  2021-10-25
68    PEFA 2016                                                             PF6              4  2021-12-06
69    Global Financial Inclusion and Consumer Protection Survey             RFA              3  2019-06-27
70    Economic Fitness 2                                                    EF2              3  2019-04-26
71    International Comparison Program (ICP) 2005                           IC5              4  2021-09-10
73    Global Financial Inclusion and Consumer Protection Survey (Internal)  RFI              3  2019-06-27
75    Environment, Social and Governance (ESG) Data                         ESG              3  2021-10-28
76    Remittance Prices Worldwide (Sending Countries)                       RWS              3  2020-12-07
77    Remittance Prices Worldwide (Receiving Countries)                     RWR              3  2020-12-07
78    ICP 2017                                                              IC7              4  2020-10-21
79    PEFA_GRPFM                                                            GRP              4  2021-10-27
80    Gender Disaggregated Labor Database (GDLD)                            GDL              4  2020-07-25
81    International Debt Statistics: DSSI                                   DSI              4  2021-10-10
82    Global Public Procurement                                             GPP              3  2021-03-24
83    Statistical Performance Indicators (SPI)                              SPI              3  2021-04-01
84    Education Policy                                                      EDP              3  2021-05-11
85    PEFA_2021_SNG                                                         SNG              4  2021-10-06
86    Global Jobs Indicators Database (JOIN)                                JON              3  2021-09-24
87    Country Climate and Development Report (CCDR)                         CCD              3  2021-10-08
      67 elements

In [31]:
wb.series.info(q='teachers')

id                    value
--------------------  ----------------------------------------------------------------------------
SE.PRE.TCAQ.FE.ZS     Trained teachers in preprimary education, female (% of female teachers)
SE.PRE.TCAQ.MA.ZS     Trained teachers in preprimary education, male (% of male teachers)
SE.PRE.TCAQ.ZS        Trained teachers in preprimary education (% of total teachers)
SE.PRM.TCAQ.FE.ZS     Trained teachers in primary education, female (% of female teachers)
SE.PRM.TCAQ.MA.ZS     Trained teachers in primary education, male (% of male teachers)
SE.PRM.TCAQ.ZS        Trained teachers in primary education (% of total teachers)
SE.PRM.TCHR           Primary education, teachers
SE.PRM.TCHR.FE.ZS     Primary education, teachers (% female)
SE.SEC.TCAQ.FE.ZS     Trained teachers in secondary education, female (% of female teachers)
SE.SEC.TCAQ.LO.FE.ZS  Trained teachers in lower secondary education, female (% of female teachers)
SE.SEC.TCAQ.LO.MA.ZS  Trained teachers in lower secondary education, male (% of male teachers)
SE.SEC.TCAQ.LO.ZS     Trained teachers in lower secondary education (% of total teachers)
SE.SEC.TCAQ.MA.ZS     Trained teachers in secondary education, male (% of male teachers)
SE.SEC.TCAQ.UP.FE.ZS  Trained teachers in upper secondary education, female (% of female teachers)
SE.SEC.TCAQ.UP.MA.ZS  Trained teachers in upper secondary education, male (% of male teachers)
SE.SEC.TCAQ.UP.ZS     Trained teachers in upper secondary education (% of total teachers)
SE.SEC.TCAQ.ZS        Trained teachers in secondary education (% of total teachers)
SE.SEC.TCHR           Secondary education, teachers
SE.SEC.TCHR.FE        Secondary education, teachers, female
SE.SEC.TCHR.FE.ZS     Secondary education, teachers (% female)
                      20 elements

In [16]:
eduAttainmentSecondary = wb.data.DataFrame('SE.SEC.CUAT.UP.ZS', wb.region.members('WLD'), time=range(2018,2019))
eduAttainmentSecondary.head(50)

         SE.SEC.CUAT.UP.ZS
economy
ABW                    NaN
AFG                    NaN
AGO                    NaN
ALB                    NaN
AND                    NaN
ARE              69.140160
ARG                    NaN
ARM                    NaN
ASM                    NaN
ATG                    NaN
AUS              78.325760
AUT                    NaN
AZE                    NaN
BDI                    NaN
BEL                    NaN
BEN                    NaN
BFA               6.152450
BGD              30.544769
BGR                    NaN
BHR              64.928230
BHS                    NaN
BIH              63.506538
BLR                    NaN
BLZ                    NaN
BMU                    NaN
BOL                    NaN
BRA              47.432869
BRB                    NaN
BRN                    NaN
BTN                    NaN
BWA                    NaN
CAF                    NaN
CAN                    NaN
CHE              85.681770
CHI                    NaN
CHL                    NaN
CHN                    NaN
CIV                    NaN
CMR                    NaN
COD                    NaN
COG                    NaN
COL              49.774479
COM                    NaN
CPV                    NaN
CRI              39.656731
CUB                    NaN
CUW                    NaN
CYM                    NaN
CYP              72.981354
CZE                    NaN

In [19]:
#School enrollment, primary (% net)
accessPrimary = wb.data.DataFrame('SE.PRM.NENR', wb.region.members('WLD'), time=range(2018,2019))
accessPrimary.head(50)

         SE.PRM.NENR
economy
ABW              NaN
AFG              NaN
AGO              NaN
ALB         94.52966
AND              NaN
ARE              NaN
ARG              NaN
ARM         90.72273
ASM              NaN
ATG         95.69547
AUS              NaN
AUT              NaN
AZE         92.42467
BDI         92.80470
BEL              NaN
BEN         97.21103
BFA         78.64517
BGD              NaN
BGR              NaN
BHR         96.71489
BHS         74.22717
BIH              NaN
BLR         94.92861
BLZ         95.94237
BMU              NaN
BOL         92.85137
BRA              NaN
BRB         96.69287
BRN         93.14673
BTN         88.02597
BWA              NaN
CAF              NaN
CAN              NaN
CHE              NaN
CHI              NaN
CHL              NaN
CHN              NaN
CIV         90.32837
CMR              NaN
COD              NaN
COG              NaN
COL         92.91999
COM         80.75383
CPV         93.42191
CRI         97.33255
CUB         97.73994
CUW              NaN
CYM              NaN
CYP              NaN
CZE              NaN

In [22]:
#Primary school starting age (years)
agePrimary = wb.data.DataFrame('SE.PRM.AGES', wb.region.members('WLD'), time=range(2018,2019))
agePrimary.head(50)

         SE.PRM.AGES
economy
ABW              6.0
AFG              7.0
AGO              6.0
ALB              6.0
AND              6.0
ARE              6.0
ARG              6.0
ARM              6.0
ASM              6.0
ATG              5.0
AUS              5.0
AUT              6.0
AZE              6.0
BDI              7.0
BEL              6.0
BEN              6.0
BFA              6.0
BGD              6.0
BGR              7.0
BHR              6.0
BHS              5.0
BIH              6.0
BLR              6.0
BLZ              5.0
BMU              5.0
BOL              6.0
BRA              6.0
BRB              5.0
BRN              6.0
BTN              6.0
BWA              6.0
CAF              6.0
CAN              6.0
CHE              7.0
CHI              NaN
CHL              6.0
CHN              6.0
CIV              6.0
CMR              6.0
COD              6.0
COG              6.0
COL              6.0
COM              6.0
CPV              6.0
CRI              6.0
CUB              6.0
CUW              6.0
CYM              5.0
CYP              6.0
CZE              6.0

In [33]:
#Literacy rate, youth total (% of people ages 15-24)
literacy = wb.data.DataFrame('SE.ADT.1524.LT.ZS', wb.region.members('WLD'), time=range(2018,2019))
literacy.head(50)

         SE.PRM.TCAQ.ZS
economy
ABW                 NaN
AFG                 NaN
AGO                 NaN
ALB           89.920807
AND          100.000000
...                 ...
TTO                 NaN
TUN          100.000000
TUR                 NaN
TUV           80.000000
TZA                 NaN

[200 rows x 1 columns]

In [34]:
literacy.to_csv(r'/Users/maxime/IronHack/Projects/Project2/literacy.csv')